version: '3'

services:
   gerrit:
      restart: unless-stopped
      container_name: gerrit
      image: gerritcodereview/gerrit:3.8.0
      volumes:
         - git-volume:/var/gerrit/git
         - index-volume:/var/gerrit/index
         - cache-volume:/var/gerrit/cache
      ports:
         - "29418:29418"
         - "8086:8080"
      environment:
         - "CANONICAL_WEB_URL=http://localhost:8086"

volumes:
   git-volume:
   index-volume:
   cache-volume:
